// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8eUWhxLZE4hAH6OWjUmZChX0TK_y_DEs',
    appId: '1:330182934928:web:d60085ca9b894e5b71b315',
    messagingSenderId: '330182934928',
    projectId: 'fir-practice-4a8ac',
    authDomain: 'fir-practice-4a8ac.firebaseapp.com',
    storageBucket: 'fir-practice-4a8ac.appspot.com',
    measurementId: 'G-DC5Y0BQQ8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiTYYPO-EW2UBHspjotiZag86z-DIDhOk',
    appId: '1:330182934928:android:3df3cfdd652b025f71b315',
    messagingSenderId: '330182934928',
    projectId: 'fir-practice-4a8ac',
    storageBucket: 'fir-practice-4a8ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHm0b5W6qqb5BcufAXfm7puTfT3FwzcX4',
    appId: '1:330182934928:ios:0c3541002e0ea26471b315',
    messagingSenderId: '330182934928',
    projectId: 'fir-practice-4a8ac',
    storageBucket: 'fir-practice-4a8ac.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHm0b5W6qqb5BcufAXfm7puTfT3FwzcX4',
    appId: '1:330182934928:ios:28062b629528e1ec71b315',
    messagingSenderId: '330182934928',
    projectId: 'fir-practice-4a8ac',
    storageBucket: 'fir-practice-4a8ac.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
